variable "vpc_cidr" {
  description = "CIDR assinged to VPC"
  type        = string
}

variable "vpc_assign_ipv6_cidr" {
  description = "Assign an autogenerated IPV6 CIDR Block"
  type        = bool
  default     = false
}

variable "vpc_availability_zones" {
  description = "Map consistiong ok availabiltiy zones names as keys and their def. as value"
  type = map(object({
    public_subnet_cidr   = string
    private_subnets_cidr = list(string)
    tags                 = map(string)
  }))
  default = {}
}

variable "vpc_pcxs" {
  description = "List of VPC id's to which created VPC should be peered"
  type = list(object({
    vpc_id         = string
    peer_route_ids = list(string)
  }))
  default = []
}

variable "vpc_endpoint_s3_policy" {
  description = "S3 VPC Endpoint policy content"
  type        = string
  default     = <<POLICY
{
	"Statement": [
		{
			"Action": [
				"s3:ListBucket",
				"s3:PutObject",
				"s3:GetObject",
				"s3:DeleteObject",
				"s3:GetObjectTagging"
			],
			"Effect": "Allow",
			"Resource": "arn:aws:s3:::*",
			"Principal": "*"
		}
	],
	"Version": "2008-10-17"
}
POLICY
}

variable "vpc_tags" {
  description = "List of tags added to VPC"
  type        = map(string)
  default     = {}
}
